[WIP] Support join() directly on Mapping
tithely/picomapper pull request #18
Opened 2023-01-11 18:43 UTC by CoreyRDean

2023-01-17 04:27 UTC, joshmcrae requested changes
I can't see any issues with these changes, aside from the formatting which I've commented on below.

2023-01-17 04:27 UTC, joshmcrae commented on src/Mapping.php
> +        $table = $this->definition->getTable();
Some whitespace between logical 'paragraphs' will make this method more readable.

2023-01-17 19:43 UTC, CoreyRDean commented
@joshmcrae should be better formatted now.

2023-06-06 03:08 UTC, b-hayes commented
any reason this was never merged?

2023-06-06 03:23 UTC, joshmcrae commented
@b-hayes I was just about to look into this today actually. I don't have any outstanding issue with the code as it is, but would appreciate some manual testing of the code even though we've got passing unit tests.

Is this something you're able to help with? I'm happy to create a pre-release if that makes thing easier.

2023-06-29 01:23 UTC, joshmcrae requested changes
@CoreyRDean I've spent some time looking over this PR again and have been running it locally to test it in a real project. Functionally I can't find any faults, though there are aspects of the code changes that could be clarified.

I've left some comments on specific areas I'm having trouble understanding, or that I otherwise believe could be simplified. Once those are addressed we can do some further testing and get this released.

If you don't feel like these changes are necessary anymore, we could alternatively close this one out.

2023-06-29 01:23 UTC, joshmcrae commented on src/Mapping.php
> +            $required[] = in_array($item->getLocalColumn(), $this->definition->getPrimaryKey()) ? $this->prefixTableNameTo($item->getLocalColumn()) : $item->getLocalColumn();
@CoreyRDean is the logic in this ternary necessary, given that line 585 is prefixing all unprefixed columns with the definition's table anyway (effectively the same logic as `prefixTableNameTo()`)?

2023-06-29 01:23 UTC, joshmcrae commented on src/Mapping.php
>          foreach (array_unique($required) as $column) {
This is already preventing duplicates, however it's possible that the primary key columns which are already included in the `$columns` array are repeated in `$required`. Do we need to do further deduplication?

It's obviously working as it is, but there would be duplicate columns specified in the generated SQL.

2023-06-29 01:23 UTC, joshmcrae commented on src/Mapping.php
> +                    $key = $this->prefixTableNameTo($key);
I couldn't find anywhere that this function is applied to a dictionary. If we're not applying it to dictionary keys, we should remove this code to make it more readable.

2023-07-02 23:14 UTC, joshmcrae approved these changes

2023-07-10 21:40 UTC, merged

2023-07-10 23:30 UTC, joshmcrae commented
Released as [2.2.0](https://github.com/tithely/picomapper/releases/tag/2.2.0).